In [283]:
import pandas as pd
import numpy as np
from sklearn import preprocessing 
from scipy import stats

In [284]:
data = pd.read_csv('/content/train_data.csv')
data.head()

   Unnamed: 0   Id  MSSubClass  ... SaleType  SaleCondition  SalePrice
0         618  619          20  ...      New        Partial     314813
1         870  871          20  ...       WD         Normal     109500
2          92   93          30  ...       WD         Normal     163500
3         817  818          20  ...       WD         Normal     271000
4         302  303          20  ...       WD         Normal     205000

[5 rows x 82 columns]

In [285]:
data = data.drop('Unnamed: 0', axis= 1)

In [286]:
data.describe(include= 'all')

                 Id   MSSubClass  ... SaleCondition      SalePrice
count   1168.000000  1168.000000  ...          1168    1168.000000
unique          NaN          NaN  ...             6            NaN
top             NaN          NaN  ...        Normal            NaN
freq            NaN          NaN  ...           969            NaN
mean     738.685788    56.605308  ...           NaN  180808.898973
std      421.609683    42.172322  ...           NaN   78499.911304
min        1.000000    20.000000  ...           NaN   34900.000000
25%      373.750000    20.000000  ...           NaN  130000.000000
50%      749.500000    50.000000  ...           NaN  163000.000000
75%     1108.750000    70.000000  ...           NaN  215000.000000
max     1460.000000   190.000000  ...           NaN  755000.000000

[11 rows x 81 columns]

In [287]:
data.isna().sum().sum()

5541

In [ ]:
columns = data.columns

In [ ]:
cc = (data.dtypes == 'object')
categorical_columns = []
i = 0
for cols in cc:
  if cols == True:
    categorical_columns.append(columns[i])
    print(columns[i])
  i += 1

categorical_columns

In [290]:
le = preprocessing.LabelEncoder()
labelled_data = data.copy()
for col in categorical_columns:
  labelled_data[col] = le.fit_transform(data[col])

In [ ]:
missing_data = []
j = 0
for cols in data.columns:
  if data[cols].isna().sum() >= 1:
    missing_data.append(columns[j])
  j += 1

missing_data

In [292]:
complete_data = labelled_data.copy()
for col in missing_data:
  for col2 in categorical_columns:
    if col == col2:
      complete_data[col] = labelled_data[col].fillna(0)
    else:
      break
  complete_data[col] = labelled_data[col].fillna(labelled_data[col].mean())

In [293]:
complete_data.isna().sum().sum()

0

In [294]:
Y = complete_data['SalePrice']
X = complete_data.drop('SalePrice', axis= 1)

In [295]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, Y_test = train_test_split(X, Y, test_size = 0.25)

In [296]:
from sklearn.ensemble import RandomForestRegressor

In [297]:
rf.fit(X_train, y_train)
rf.score(X_test, Y_test)

0.8699616792362351